/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package furniture_shop;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Musab
 */
public class bed extends javax.swing.JFrame {
Connection con1;
     PreparedStatement insert;
    /**
     * Creates new form bed
     */
    public bed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bedtabs = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addtocartbtn10 = new javax.swing.JButton();
        addtocartbtn11 = new javax.swing.JButton();
        addtocartbtn12 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        nameitemlabel12 = new javax.swing.JLabel();
        nameitemlabel13 = new javax.swing.JLabel();
        nameitemlabel14 = new javax.swing.JLabel();
        pricechair11 = new javax.swing.JLabel();
        pricechair12 = new javax.swing.JLabel();
        pricechair13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addtocartbtn13 = new javax.swing.JButton();
        addtocartbtn14 = new javax.swing.JButton();
        addtocartbtn15 = new javax.swing.JButton();
        nameitemlabel15 = new javax.swing.JLabel();
        nameitemlabel16 = new javax.swing.JLabel();
        nameitemlabel17 = new javax.swing.JLabel();
        pricechair14 = new javax.swing.JLabel();
        pricechair15 = new javax.swing.JLabel();
        pricechair16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BedLabel = new javax.swing.JLabel();
        checkoutbtn = new javax.swing.JButton();
        menubtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/single bed 1.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/single bed 2.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/single bed 3.jpg"))); // NOI18N

        addtocartbtn10.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn10.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn10.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn10.setText("ADD TO CART");
        addtocartbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn10ActionPerformed(evt);
            }
        });

        addtocartbtn11.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn11.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn11.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn11.setText("ADD TO CART");
        addtocartbtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn11ActionPerformed(evt);
            }
        });

        addtocartbtn12.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn12.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn12.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn12.setText("ADD TO CART");
        addtocartbtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn12ActionPerformed(evt);
            }
        });

        nameitemlabel12.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel12.setText("Daisen single bed");

        nameitemlabel13.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel13.setText("Beryl Single bed");

        nameitemlabel14.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel14.setText("Winston single bed");

        pricechair11.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair11.setText("PRICE: RS 49,000");

        pricechair12.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair12.setText("PRICE: RS 53,000");

        pricechair13.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair13.setText("PRICE: RS 66,000");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addtocartbtn12)
                            .addComponent(addtocartbtn11)
                            .addComponent(addtocartbtn10)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameitemlabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameitemlabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pricechair12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(317, 317, 317))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(pricechair11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(334, 334, 334))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(nameitemlabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(pricechair13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(335, 335, 335))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(nameitemlabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pricechair11)
                        .addGap(34, 34, 34)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(addtocartbtn10)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(addtocartbtn11)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(nameitemlabel12)
                        .addGap(69, 69, 69)
                        .addComponent(pricechair12)))
                .addGap(74, 74, 74)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(nameitemlabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pricechair13)
                        .addGap(80, 80, 80)))
                .addComponent(addtocartbtn12)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        bedtabs.addTab("Single bed", jPanel2);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/double bed 1.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/double bed 2.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/double bed 3.jpg"))); // NOI18N

        addtocartbtn13.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn13.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn13.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn13.setText("ADD TO CART");
        addtocartbtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn13ActionPerformed(evt);
            }
        });

        addtocartbtn14.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn14.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn14.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn14.setText("ADD TO CART");
        addtocartbtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn14ActionPerformed(evt);
            }
        });

        addtocartbtn15.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn15.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn15.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn15.setText("ADD TO CART");
        addtocartbtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn15ActionPerformed(evt);
            }
        });

        nameitemlabel15.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel15.setText("Elder Double bed");

        nameitemlabel16.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel16.setText("Hoffman Double bed");

        nameitemlabel17.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel17.setText("Andrea Double bed");

        pricechair14.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair14.setText("PRICE: RS 110,000");

        pricechair15.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair15.setText("PRICE: RS 130,000");

        pricechair16.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair16.setText("PRICE: RS 90,000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(pricechair14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameitemlabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameitemlabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(pricechair15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(nameitemlabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(pricechair16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)))
                .addGap(235, 235, 235))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(addtocartbtn15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addtocartbtn13)
                            .addComponent(addtocartbtn14))))
                .addGap(0, 458, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(nameitemlabel17)
                        .addGap(74, 74, 74)
                        .addComponent(pricechair16)))
                .addGap(50, 50, 50)
                .addComponent(addtocartbtn13)
                .addGap(108, 108, 108)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(46, 46, 46)
                        .addComponent(addtocartbtn14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nameitemlabel15)
                        .addGap(59, 59, 59)
                        .addComponent(pricechair14)))
                .addGap(86, 86, 86)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nameitemlabel16)
                        .addGap(45, 45, 45)
                        .addComponent(pricechair15))
                    .addComponent(jLabel6))
                .addGap(56, 56, 56)
                .addComponent(addtocartbtn15)
                .addContainerGap(536, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bedtabs.addTab("Double Bed", jPanel3);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        BedLabel.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        BedLabel.setForeground(new java.awt.Color(255, 255, 255));
        BedLabel.setText("BEDS");

        checkoutbtn.setBackground(new java.awt.Color(0, 0, 0));
        checkoutbtn.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        checkoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutbtn.setText("CHECK OUT");
        checkoutbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutbtnActionPerformed(evt);
            }
        });

        menubtn.setBackground(new java.awt.Color(0, 0, 0));
        menubtn.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        menubtn.setForeground(new java.awt.Color(255, 255, 255));
        menubtn.setText("MENU");
        menubtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menubtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BedLabel)
                .addGap(198, 198, 198)
                .addComponent(checkoutbtn)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BedLabel)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bedtabs)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bedtabs, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubtnActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menubtnActionPerformed

    private void checkoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutbtnActionPerformed
        // TODO add your handling code here:
        Billing b = new Billing();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkoutbtnActionPerformed

    private void addtocartbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn10ActionPerformed
        // TODO add your handling code here:
        String Product = "Beryl Single Bed";
        String Qty = "1";
        String Price = "49000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn10ActionPerformed

    private void addtocartbtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn11ActionPerformed
        // TODO add your handling code here:
        String Product = "Daisen Single Bed";
        String Qty = "1";
        String Price = "53000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn11ActionPerformed

    private void addtocartbtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn12ActionPerformed
        // TODO add your handling code here:
        String Product = "Winstor Single Bed";
        String Qty = "1";
        String Price = "66000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn12ActionPerformed

    private void addtocartbtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn13ActionPerformed
        // TODO add your handling code here:
        String Product = "Andrea Double bed";
        String Qty = "1";
        String Price = "90000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn13ActionPerformed

    private void addtocartbtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn14ActionPerformed
        // TODO add your handling code here:
        String Product = "Elder Double Bed";
        String Qty = "1";
        String Price = "110000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn14ActionPerformed

    private void addtocartbtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn15ActionPerformed
        // TODO add your handling code here:
        String Product = "Hoffman Double Bed";
        String Qty = "1";
        String Price = "130000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BedLabel;
    private javax.swing.JButton addtocartbtn10;
    private javax.swing.JButton addtocartbtn11;
    private javax.swing.JButton addtocartbtn12;
    private javax.swing.JButton addtocartbtn13;
    private javax.swing.JButton addtocartbtn14;
    private javax.swing.JButton addtocartbtn15;
    private javax.swing.JTabbedPane bedtabs;
    private javax.swing.JButton checkoutbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton menubtn;
    private javax.swing.JLabel nameitemlabel12;
    private javax.swing.JLabel nameitemlabel13;
    private javax.swing.JLabel nameitemlabel14;
    private javax.swing.JLabel nameitemlabel15;
    private javax.swing.JLabel nameitemlabel16;
    private javax.swing.JLabel nameitemlabel17;
    private javax.swing.JLabel pricechair11;
    private javax.swing.JLabel pricechair12;
    private javax.swing.JLabel pricechair13;
    private javax.swing.JLabel pricechair14;
    private javax.swing.JLabel pricechair15;
    private javax.swing.JLabel pricechair16;
    // End of variables declaration//GEN-END:variables
}
