/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package furniture_shop;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Musab
 */
public class chair extends javax.swing.JFrame {

    /**
     * Creates new form chair
     */
     Connection con1;
     PreparedStatement insert;
    public chair() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedshelves = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        addtocartbtn10 = new javax.swing.JButton();
        addtocartbtn11 = new javax.swing.JButton();
        addtocartbtn12 = new javax.swing.JButton();
        addtocartbtn13 = new javax.swing.JButton();
        addtocartbtn14 = new javax.swing.JButton();
        addtocartbtn15 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pricechair6 = new javax.swing.JLabel();
        pricechair7 = new javax.swing.JLabel();
        pricechair8 = new javax.swing.JLabel();
        pricechair9 = new javax.swing.JLabel();
        pricechair10 = new javax.swing.JLabel();
        pricechair11 = new javax.swing.JLabel();
        nameitemlabel7 = new javax.swing.JLabel();
        nameitemlabel8 = new javax.swing.JLabel();
        nameitemlabel9 = new javax.swing.JLabel();
        nameitemlabel10 = new javax.swing.JLabel();
        nameitemlabel11 = new javax.swing.JLabel();
        nameitemlabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addtocartbtn16 = new javax.swing.JButton();
        addtocartbtn17 = new javax.swing.JButton();
        addtocartbtn18 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        pricechair = new javax.swing.JLabel();
        pricechair1 = new javax.swing.JLabel();
        pricechair2 = new javax.swing.JLabel();
        nameitemlabel4 = new javax.swing.JLabel();
        nameitemlabel5 = new javax.swing.JLabel();
        nameitemlabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        addtocartbtn19 = new javax.swing.JButton();
        addtocartbtn20 = new javax.swing.JButton();
        addtocartbtn21 = new javax.swing.JButton();
        addtocartbtn22 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        pricechair3 = new javax.swing.JLabel();
        pricechair4 = new javax.swing.JLabel();
        pricechair5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nameitemlabel = new javax.swing.JLabel();
        nameitemlabel1 = new javax.swing.JLabel();
        nameitemlabel2 = new javax.swing.JLabel();
        nameitemlabel3 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Chairheading = new javax.swing.JLabel();
        checkoutbtn = new javax.swing.JButton();
        menubtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabbedshelves.setBackground(new java.awt.Color(255, 255, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        addtocartbtn10.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn10.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn10.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn10.setText("ADD TO CART");
        addtocartbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn10ActionPerformed(evt);
            }
        });

        addtocartbtn11.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn11.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn11.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn11.setText("ADD TO CART");
        addtocartbtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn11ActionPerformed(evt);
            }
        });

        addtocartbtn12.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn12.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn12.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn12.setText("ADD TO CART");
        addtocartbtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn12ActionPerformed(evt);
            }
        });

        addtocartbtn13.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn13.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn13.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn13.setText("ADD TO CART");
        addtocartbtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn13ActionPerformed(evt);
            }
        });

        addtocartbtn14.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn14.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn14.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn14.setText("ADD TO CART");
        addtocartbtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn14ActionPerformed(evt);
            }
        });

        addtocartbtn15.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn15.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn15.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn15.setText("ADD TO CART");
        addtocartbtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn15ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/Dining chair 1.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/dining chair 2.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/dining chair 3.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/visitor chair 1.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/visitor chair 2.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/visitor chair 3.jpg"))); // NOI18N

        pricechair6.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair6.setText("PRICE: RS 31,000");

        pricechair7.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair7.setText("PRICE: RS 33,000");

        pricechair8.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair8.setText("PRICE: RS 15,000");

        pricechair9.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair9.setText("PRICE: RS 11,000");

        pricechair10.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair10.setText("PRICE: RS 29,000");

        pricechair11.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair11.setText("PRICE: RS 19,000");

        nameitemlabel7.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel7.setText("Visitors Sofa Chair");

        nameitemlabel8.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel8.setText("Jarin Visitors chair ");

        nameitemlabel9.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel9.setText("Prahl Visitors chair ");

        nameitemlabel10.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel10.setText("Betina");

        nameitemlabel11.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel11.setText("Luigi");

        nameitemlabel12.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel12.setText("Jurge Dinning chairs");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addtocartbtn10)
                        .addGap(270, 270, 270))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(addtocartbtn11))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(addtocartbtn12)))
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(addtocartbtn15)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(addtocartbtn13)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(addtocartbtn14)
                        .addGap(275, 275, 275))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(pricechair7))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(nameitemlabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(pricechair6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(nameitemlabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(pricechair10))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(nameitemlabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(pricechair8))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(nameitemlabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(121, 121, 121))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(pricechair9))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(nameitemlabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(nameitemlabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(pricechair11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(98, 98, 98))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(nameitemlabel12)
                        .addGap(72, 72, 72)
                        .addComponent(pricechair11)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(addtocartbtn10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addGap(21, 21, 21)
                                        .addComponent(addtocartbtn11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(addtocartbtn12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(380, 380, 380)
                                        .addComponent(nameitemlabel10)
                                        .addGap(100, 100, 100)
                                        .addComponent(pricechair8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(722, 722, 722)
                                .addComponent(nameitemlabel9)
                                .addGap(111, 111, 111)
                                .addComponent(pricechair10)
                                .addGap(75, 75, 75)))
                        .addComponent(addtocartbtn13)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(nameitemlabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pricechair7)
                                .addGap(94, 94, 94)))
                        .addComponent(addtocartbtn14)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(addtocartbtn15))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(nameitemlabel7)
                                .addGap(123, 123, 123)
                                .addComponent(pricechair6))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(nameitemlabel11)
                        .addGap(79, 79, 79)
                        .addComponent(pricechair9)))
                .addContainerGap(972, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedshelves.addTab("Dinning and Visitors Chairs", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 255, 0));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/bar stools 1.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/bar stools 2.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/bar stools 3.jpg"))); // NOI18N

        addtocartbtn16.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn16.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn16.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn16.setText("ADD TO CART");
        addtocartbtn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn16ActionPerformed(evt);
            }
        });

        addtocartbtn17.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn17.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn17.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn17.setText("ADD TO CART");
        addtocartbtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn17ActionPerformed(evt);
            }
        });

        addtocartbtn18.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn18.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn18.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn18.setText("ADD TO CART");
        addtocartbtn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn18ActionPerformed(evt);
            }
        });

        pricechair.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair.setText("PRICE: RS 13,000");

        pricechair1.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair1.setText("PRICE: RS 22,000");

        pricechair2.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair2.setText("PRICE: RS 18,000");

        nameitemlabel4.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel4.setText("Bar Chair");

        nameitemlabel5.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel5.setText("BAR Stools");

        nameitemlabel6.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel6.setText("Steel Stools");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pricechair2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameitemlabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(356, 356, 356))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(addtocartbtn16))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(295, 295, 295)
                                .addComponent(addtocartbtn18))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(pricechair))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(114, 114, 114)
                                    .addComponent(nameitemlabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(131, 131, 131)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(pricechair1))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(nameitemlabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(181, 181, 181)
                        .addComponent(jLabel8))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(addtocartbtn17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(nameitemlabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pricechair)
                        .addGap(87, 87, 87)))
                .addComponent(addtocartbtn16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(nameitemlabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pricechair1)
                        .addGap(143, 143, 143))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel8)
                        .addGap(48, 48, 48)))
                .addComponent(addtocartbtn17)
                .addGap(83, 83, 83)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel9))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(nameitemlabel6)
                        .addGap(125, 125, 125)
                        .addComponent(pricechair2)))
                .addGap(39, 39, 39)
                .addComponent(addtocartbtn18)
                .addContainerGap(2302, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedshelves.addTab("Bar Stools", jPanel3);

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/shelves 1.jpg"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/shelves 2.jpg"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/shelves 3.jpg"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/shelves 4.jpg"))); // NOI18N

        addtocartbtn19.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn19.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn19.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn19.setText("ADD TO CART");
        addtocartbtn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn19ActionPerformed(evt);
            }
        });

        addtocartbtn20.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn20.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn20.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn20.setText("ADD TO CART");
        addtocartbtn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn20ActionPerformed(evt);
            }
        });

        addtocartbtn21.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn21.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn21.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn21.setText("ADD TO CART");
        addtocartbtn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn21ActionPerformed(evt);
            }
        });

        addtocartbtn22.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn22.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn22.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn22.setText("ADD TO CART");
        addtocartbtn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn22ActionPerformed(evt);
            }
        });

        pricechair3.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair3.setText("PRICE: RS 14,000");

        pricechair4.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair4.setText("PRICE: RS 20,000");

        pricechair5.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair5.setText("PRICE: RS 25,000");

        jLabel14.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jLabel14.setText("PRICE: RS 30,000");

        nameitemlabel.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel.setText("Zig Zag Book Shelves");

        nameitemlabel1.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel1.setText("Three row wooden shelve");

        nameitemlabel2.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel2.setText("ARC Book Shelve");

        nameitemlabel3.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel3.setText("Wall Box Shelves");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel14))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nameitemlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pricechair5))))
                        .addGap(100, 100, 100)
                        .addComponent(jLabel11))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(nameitemlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel10))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pricechair4)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(nameitemlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(pricechair3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(nameitemlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(addtocartbtn19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(addtocartbtn20))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(addtocartbtn21)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel12))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(addtocartbtn22))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(902, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(nameitemlabel1)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel14)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(addtocartbtn19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(nameitemlabel3)
                        .addGap(85, 85, 85)
                        .addComponent(pricechair5)
                        .addGap(74, 74, 74))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)))
                .addComponent(addtocartbtn20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(nameitemlabel)
                        .addGap(112, 112, 112)
                        .addComponent(pricechair4)
                        .addGap(101, 101, 101)
                        .addComponent(addtocartbtn21)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel13)
                                .addGap(41, 41, 41))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(nameitemlabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pricechair3)
                                .addGap(78, 78, 78)))
                        .addComponent(addtocartbtn22))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel12)))
                .addContainerGap(2585, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedshelves.addTab("Shelves, Racks & others", jPanel4);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        Chairheading.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        Chairheading.setForeground(new java.awt.Color(255, 255, 255));
        Chairheading.setText("CHAIRS, BARS & OTHERS");

        checkoutbtn.setBackground(new java.awt.Color(0, 0, 0));
        checkoutbtn.setFont(new java.awt.Font("Segoe Print", 3, 12)); // NOI18N
        checkoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutbtn.setText("CHECK OUT");
        checkoutbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkoutbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutbtnActionPerformed(evt);
            }
        });

        menubtn.setBackground(new java.awt.Color(0, 0, 0));
        menubtn.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        menubtn.setForeground(new java.awt.Color(255, 255, 255));
        menubtn.setText("MENU");
        menubtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menubtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Chairheading)
                .addGap(48, 48, 48)
                .addComponent(checkoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Chairheading)
                            .addComponent(menubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(checkoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedshelves, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedshelves, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addtocartbtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn15ActionPerformed
        // TODO add your handling code here:
        String Product = "Visitor sofa chair";
        String Qty = "1";
        String Price = "31000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 

    }//GEN-LAST:event_addtocartbtn15ActionPerformed

    private void menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubtnActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menubtnActionPerformed

    private void checkoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutbtnActionPerformed
        // TODO add your handling code here:
        Billing b = new Billing();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkoutbtnActionPerformed

    private void addtocartbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn10ActionPerformed
        // TODO add your handling code here:
        String Product = "Jurge Dining chair";
        String Qty = "1";
        String Price = "19000";
        
       
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
            updatejtable1();
            
            
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 


    }//GEN-LAST:event_addtocartbtn10ActionPerformed

    private void addtocartbtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn11ActionPerformed
        // TODO add your handling code here:
        String Product = "Luigi";
        String Qty = "1";
        String Price = "11000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn11ActionPerformed

    private void addtocartbtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn12ActionPerformed
        // TODO add your handling code here:
        String Product = "Betina";
        String Qty = "1";
        String Price = "15000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn12ActionPerformed

    private void addtocartbtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn13ActionPerformed
        // TODO add your handling code here:
        String Product = "Parhl Visitor chair";
        String Qty = "1";
        String Price = "29000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn13ActionPerformed

    private void addtocartbtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn14ActionPerformed
        // TODO add your handling code here:
        String Product = "Jarin Visitors chair";
        String Qty = "1";
        String Price = "33000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn14ActionPerformed

    private void addtocartbtn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn16ActionPerformed
        // TODO add your handling code here:
        String Product = "Bar Chair";
        String Qty = "1";
        String Price = "13000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn16ActionPerformed

    private void addtocartbtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn17ActionPerformed
        // TODO add your handling code here:
        String Product = "Bar stool";
        String Qty = "1";
        String Price = "22000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn17ActionPerformed

    private void addtocartbtn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn18ActionPerformed
        // TODO add your handling code here:
        String Product = "Steel Stool";
        String Qty = "1";
        String Price = "18000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn18ActionPerformed

    private void addtocartbtn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn19ActionPerformed
        // TODO add your handling code here:
        String Product = "Three row wooden shelve";
        String Qty = "1";
        String Price = "30000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn19ActionPerformed

    private void addtocartbtn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn20ActionPerformed
        // TODO add your handling code here:
        String Product = "Wall box shelves";
        String Qty = "1";
        String Price = "25000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn20ActionPerformed

    private void addtocartbtn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn21ActionPerformed
        // TODO add your handling code here:
        String Product = "Zig Zag book Shelves";
        String Qty = "1";
        String Price = "20000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn21ActionPerformed

    private void addtocartbtn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn22ActionPerformed
        // TODO add your handling code here:
        String Product = "Arc Book Shelves";
        String Qty = "1";
        String Price = "14000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn22ActionPerformed




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chair.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chair().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Chairheading;
    private javax.swing.JButton addtocartbtn10;
    private javax.swing.JButton addtocartbtn11;
    private javax.swing.JButton addtocartbtn12;
    private javax.swing.JButton addtocartbtn13;
    private javax.swing.JButton addtocartbtn14;
    private javax.swing.JButton addtocartbtn15;
    private javax.swing.JButton addtocartbtn16;
    private javax.swing.JButton addtocartbtn17;
    private javax.swing.JButton addtocartbtn18;
    private javax.swing.JButton addtocartbtn19;
    private javax.swing.JButton addtocartbtn20;
    private javax.swing.JButton addtocartbtn21;
    private javax.swing.JButton addtocartbtn22;
    private javax.swing.JButton checkoutbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton menubtn;
    private javax.swing.JLabel nameitemlabel;
    private javax.swing.JLabel nameitemlabel1;
    private javax.swing.JLabel nameitemlabel10;
    private javax.swing.JLabel nameitemlabel11;
    private javax.swing.JLabel nameitemlabel12;
    private javax.swing.JLabel nameitemlabel2;
    private javax.swing.JLabel nameitemlabel3;
    private javax.swing.JLabel nameitemlabel4;
    private javax.swing.JLabel nameitemlabel5;
    private javax.swing.JLabel nameitemlabel6;
    private javax.swing.JLabel nameitemlabel7;
    private javax.swing.JLabel nameitemlabel8;
    private javax.swing.JLabel nameitemlabel9;
    private javax.swing.JLabel pricechair;
    private javax.swing.JLabel pricechair1;
    private javax.swing.JLabel pricechair10;
    private javax.swing.JLabel pricechair11;
    private javax.swing.JLabel pricechair2;
    private javax.swing.JLabel pricechair3;
    private javax.swing.JLabel pricechair4;
    private javax.swing.JLabel pricechair5;
    private javax.swing.JLabel pricechair6;
    private javax.swing.JLabel pricechair7;
    private javax.swing.JLabel pricechair8;
    private javax.swing.JLabel pricechair9;
    private javax.swing.JTabbedPane tabbedshelves;
    // End of variables declaration//GEN-END:variables

    private void updatejtable1() {
         Billing b = new Billing();
         
    }

    

}
