/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package furniture_shop;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Musab
 */
public class Sofa extends javax.swing.JFrame {
Connection con1;
     PreparedStatement insert;
    /**
     * Creates new form Sofa
     */
    public Sofa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        sofalabel = new javax.swing.JLabel();
        Menubtn = new javax.swing.JButton();
        checkoutbtn = new javax.swing.JButton();
        sofatabbed = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addtocartbtn10 = new javax.swing.JButton();
        nameitemlabel12 = new javax.swing.JLabel();
        pricechair11 = new javax.swing.JLabel();
        pricechair12 = new javax.swing.JLabel();
        pricechair13 = new javax.swing.JLabel();
        addtocartbtn11 = new javax.swing.JButton();
        addtocartbtn12 = new javax.swing.JButton();
        nameitemlabel13 = new javax.swing.JLabel();
        nameitemlabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameitemlabel15 = new javax.swing.JLabel();
        pricechair14 = new javax.swing.JLabel();
        addtocartbtn13 = new javax.swing.JButton();
        nameitemlabel16 = new javax.swing.JLabel();
        pricechair15 = new javax.swing.JLabel();
        nameitemlabel17 = new javax.swing.JLabel();
        pricechair16 = new javax.swing.JLabel();
        addtocartbtn14 = new javax.swing.JButton();
        addtocartbtn15 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameitemlabel18 = new javax.swing.JLabel();
        pricechair17 = new javax.swing.JLabel();
        addtocartbtn16 = new javax.swing.JButton();
        nameitemlabel19 = new javax.swing.JLabel();
        pricechair18 = new javax.swing.JLabel();
        addtocartbtn17 = new javax.swing.JButton();
        addtocartbtn18 = new javax.swing.JButton();
        nameitemlabel20 = new javax.swing.JLabel();
        pricechair19 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));

        sofalabel.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        sofalabel.setForeground(new java.awt.Color(255, 255, 255));
        sofalabel.setText("SOFAS");

        Menubtn.setBackground(new java.awt.Color(0, 0, 0));
        Menubtn.setFont(new java.awt.Font("Segoe Print", 2, 18)); // NOI18N
        Menubtn.setForeground(new java.awt.Color(255, 255, 255));
        Menubtn.setText("MENU");
        Menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenubtnActionPerformed(evt);
            }
        });

        checkoutbtn.setBackground(new java.awt.Color(0, 0, 0));
        checkoutbtn.setFont(new java.awt.Font("Segoe Print", 2, 14)); // NOI18N
        checkoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutbtn.setText("CHECK OUT");
        checkoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Menubtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sofalabel)
                .addGap(168, 168, 168)
                .addComponent(checkoutbtn)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Menubtn, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(sofalabel)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/one seater 1.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/one seater 2.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/one seater 3.jpg"))); // NOI18N

        addtocartbtn10.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn10.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn10.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn10.setText("ADD TO CART");
        addtocartbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn10ActionPerformed(evt);
            }
        });

        nameitemlabel12.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel12.setText("risinger single seater");

        pricechair11.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair11.setText("PRICE: RS 23,000");

        pricechair12.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair12.setText("PRICE: RS 25,000");

        pricechair13.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair13.setText("PRICE: RS 38,000");

        addtocartbtn11.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn11.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn11.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn11.setText("ADD TO CART");
        addtocartbtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn11ActionPerformed(evt);
            }
        });

        addtocartbtn12.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn12.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn12.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn12.setText("ADD TO CART");
        addtocartbtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn12ActionPerformed(evt);
            }
        });

        nameitemlabel13.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel13.setText("chevalier single seater");

        nameitemlabel14.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel14.setText("MArin Single Seater");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(pricechair13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(nameitemlabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(pricechair11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(70, 70, 70))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(nameitemlabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addtocartbtn11)
                            .addComponent(addtocartbtn10)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addtocartbtn12)
                .addGap(259, 259, 259))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(pricechair12)
                    .addContainerGap(408, Short.MAX_VALUE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(nameitemlabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(339, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(nameitemlabel12)
                        .addGap(63, 63, 63)
                        .addComponent(pricechair11)))
                .addGap(75, 75, 75)
                .addComponent(addtocartbtn11)
                .addGap(37, 37, 37)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addComponent(addtocartbtn10)
                .addGap(31, 31, 31)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(nameitemlabel13)
                        .addGap(64, 64, 64)
                        .addComponent(pricechair13)))
                .addGap(79, 79, 79)
                .addComponent(addtocartbtn12)
                .addContainerGap(524, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(632, 632, 632)
                    .addComponent(pricechair12)
                    .addContainerGap(1020, Short.MAX_VALUE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(542, 542, 542)
                    .addComponent(nameitemlabel14)
                    .addContainerGap(1112, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sofatabbed.addTab("One Seater", jPanel3);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/two seater 1.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/two seater 2.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/two seater 3.jpg"))); // NOI18N

        nameitemlabel15.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel15.setText("Bernice double seater");

        pricechair14.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair14.setText("PRICE: RS 70,000");

        addtocartbtn13.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn13.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn13.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn13.setText("ADD TO CART");
        addtocartbtn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn13ActionPerformed(evt);
            }
        });

        nameitemlabel16.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel16.setText("palais double seater");

        pricechair15.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair15.setText("PRICE: RS 78,000");

        nameitemlabel17.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel17.setText("Ayres double seater");

        pricechair16.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair16.setText("PRICE: RS 84,000");

        addtocartbtn14.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn14.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn14.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn14.setText("ADD TO CART");
        addtocartbtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn14ActionPerformed(evt);
            }
        });

        addtocartbtn15.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn15.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn15.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn15.setText("ADD TO CART");
        addtocartbtn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nameitemlabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(pricechair14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(pricechair16))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(nameitemlabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5)
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addGap(370, 370, 370))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(pricechair15))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(nameitemlabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(361, 361, 361))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addtocartbtn14)
                            .addComponent(addtocartbtn13)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(addtocartbtn15))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(nameitemlabel16)
                        .addGap(49, 49, 49)
                        .addComponent(pricechair14)))
                .addGap(34, 34, 34)
                .addComponent(addtocartbtn13)
                .addGap(33, 33, 33)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(128, 128, 128))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(nameitemlabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pricechair16)
                        .addGap(65, 65, 65)
                        .addComponent(addtocartbtn14)
                        .addGap(38, 38, 38)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(nameitemlabel15)
                        .addGap(39, 39, 39)
                        .addComponent(pricechair15))
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addComponent(addtocartbtn15)
                .addContainerGap(700, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel7);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        sofatabbed.addTab("Two Seater", jPanel4);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/L shaped 1.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/L shaped 2.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/L shaped 3.jpg"))); // NOI18N

        nameitemlabel18.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel18.setText("Calrinda l-shaped");

        pricechair17.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair17.setText("PRICE: RS 100,000");

        addtocartbtn16.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn16.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn16.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn16.setText("ADD TO CART");
        addtocartbtn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn16ActionPerformed(evt);
            }
        });

        nameitemlabel19.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel19.setText("corwin L-shaped");

        pricechair18.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair18.setText("PRICE: RS 99,000");

        addtocartbtn17.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn17.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn17.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn17.setText("ADD TO CART");
        addtocartbtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn17ActionPerformed(evt);
            }
        });

        addtocartbtn18.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn18.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn18.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn18.setText("ADD TO CART");
        addtocartbtn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn18ActionPerformed(evt);
            }
        });

        nameitemlabel20.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel20.setText("austin 6 l-shaped ");

        pricechair19.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        pricechair19.setText("PRICE: RS 140,000");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(pricechair19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameitemlabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)))
                .addComponent(jLabel9)
                .addGap(168, 168, 168))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(addtocartbtn18))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(pricechair17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameitemlabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nameitemlabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(35, 35, 35)))
                            .addComponent(jLabel7))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(pricechair18)
                            .addGap(104, 104, 104)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(addtocartbtn17))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(addtocartbtn16))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(179, 181, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel7))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(nameitemlabel19)
                        .addGap(60, 60, 60)
                        .addComponent(pricechair17)))
                .addGap(62, 62, 62)
                .addComponent(addtocartbtn17)
                .addGap(31, 31, 31)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(nameitemlabel18)
                        .addGap(63, 63, 63)
                        .addComponent(pricechair18)))
                .addGap(67, 67, 67)
                .addComponent(addtocartbtn16)
                .addGap(53, 53, 53)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(nameitemlabel20)
                        .addGap(58, 58, 58)
                        .addComponent(pricechair19)))
                .addGap(80, 80, 80)
                .addComponent(addtocartbtn18)
                .addContainerGap(659, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel8);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sofatabbed.addTab("L Shaped", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sofatabbed)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sofatabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenubtnActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenubtnActionPerformed

    private void checkoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutbtnActionPerformed
        // TODO add your handling code here:
        Billing b = new Billing();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkoutbtnActionPerformed

    private void addtocartbtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn11ActionPerformed
        // TODO add your handling code here:
        String Product = "Risinger Single Seater";
        String Qty = "1";
        String Price = "23000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Record Saved");
            
            
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
            
            
    }//GEN-LAST:event_addtocartbtn11ActionPerformed

    private void addtocartbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn10ActionPerformed
        // TODO add your handling code here:
        String Product = "Marin Single Seater";
        String Qty = "1";
        String Price = "25000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn10ActionPerformed

    private void addtocartbtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn12ActionPerformed
        // TODO add your handling code here:
        String Product = "Chevalier Single Seater";
        String Qty = "1";
        String Price = "38000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn12ActionPerformed

    private void addtocartbtn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn13ActionPerformed
        // TODO add your handling code here:
        String Product = "Palais Double Seater";
        String Qty = "1";
        String Price = "70000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn13ActionPerformed

    private void addtocartbtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn14ActionPerformed
        // TODO add your handling code here:
        String Product = "Ayres Double Seater";
        String Qty = "1";
        String Price = "84000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn14ActionPerformed

    private void addtocartbtn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn15ActionPerformed
        // TODO add your handling code here:
        String Product = "Bernice Double Seater";
        String Qty = "1";
        String Price = "78000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn15ActionPerformed

    private void addtocartbtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn17ActionPerformed
        // TODO add your handling code here:
        String Product = "Corwin L-Shaped";
        String Qty = "1";
        String Price = "100000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn17ActionPerformed

    private void addtocartbtn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn16ActionPerformed
        // TODO add your handling code here:
        String Product = "Calrinda L-Shaped";
        String Qty = "1";
        String Price = "99000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn16ActionPerformed

    private void addtocartbtn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn18ActionPerformed
        // TODO add your handling code here:
        String Product = "Austin 6 L-Shaped";
        String Qty = "1";
        String Price = "140000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sofa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sofa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sofa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sofa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sofa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Menubtn;
    private javax.swing.JButton addtocartbtn10;
    private javax.swing.JButton addtocartbtn11;
    private javax.swing.JButton addtocartbtn12;
    private javax.swing.JButton addtocartbtn13;
    private javax.swing.JButton addtocartbtn14;
    private javax.swing.JButton addtocartbtn15;
    private javax.swing.JButton addtocartbtn16;
    private javax.swing.JButton addtocartbtn17;
    private javax.swing.JButton addtocartbtn18;
    private javax.swing.JButton checkoutbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel nameitemlabel12;
    private javax.swing.JLabel nameitemlabel13;
    private javax.swing.JLabel nameitemlabel14;
    private javax.swing.JLabel nameitemlabel15;
    private javax.swing.JLabel nameitemlabel16;
    private javax.swing.JLabel nameitemlabel17;
    private javax.swing.JLabel nameitemlabel18;
    private javax.swing.JLabel nameitemlabel19;
    private javax.swing.JLabel nameitemlabel20;
    private javax.swing.JLabel pricechair11;
    private javax.swing.JLabel pricechair12;
    private javax.swing.JLabel pricechair13;
    private javax.swing.JLabel pricechair14;
    private javax.swing.JLabel pricechair15;
    private javax.swing.JLabel pricechair16;
    private javax.swing.JLabel pricechair17;
    private javax.swing.JLabel pricechair18;
    private javax.swing.JLabel pricechair19;
    private javax.swing.JLabel sofalabel;
    private javax.swing.JTabbedPane sofatabbed;
    // End of variables declaration//GEN-END:variables

   
    
}
