/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package furniture_shop;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
public class table extends javax.swing.JFrame {
    Connection con1;
     PreparedStatement insert;
    /**
     * Creates new form table
     */
    public table() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbfoldingtable = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        addtocartbtn8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addtocartbtn9 = new javax.swing.JButton();
        addtocartbtn10 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addtocartbtn12 = new javax.swing.JButton();
        nameitemlabel20 = new javax.swing.JLabel();
        nameitemlabel21 = new javax.swing.JLabel();
        nameitemlabel22 = new javax.swing.JLabel();
        nameitemlabel23 = new javax.swing.JLabel();
        nameitemlabel24 = new javax.swing.JLabel();
        nameitemlabel25 = new javax.swing.JLabel();
        nameitemlabel26 = new javax.swing.JLabel();
        nameitemlabel27 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        addtocartbtn5 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        addtocartbtn6 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        addtocartbtn7 = new javax.swing.JButton();
        nameitemlabel17 = new javax.swing.JLabel();
        nameitemlabel18 = new javax.swing.JLabel();
        nameitemlabel19 = new javax.swing.JLabel();
        nameitemlabel28 = new javax.swing.JLabel();
        nameitemlabel29 = new javax.swing.JLabel();
        nameitemlabel30 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addtocartbtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        addtocartbtn1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        addtocartbtn2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        addtocartbtn3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        addtocartbtn4 = new javax.swing.JButton();
        nameitemlabel12 = new javax.swing.JLabel();
        nameitemlabel13 = new javax.swing.JLabel();
        nameitemlabel14 = new javax.swing.JLabel();
        nameitemlabel15 = new javax.swing.JLabel();
        nameitemlabel16 = new javax.swing.JLabel();
        nameitemlabel31 = new javax.swing.JLabel();
        nameitemlabel32 = new javax.swing.JLabel();
        nameitemlabel33 = new javax.swing.JLabel();
        nameitemlabel34 = new javax.swing.JLabel();
        nameitemlabel35 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        headingTable = new javax.swing.JLabel();
        checkoutbtn = new javax.swing.JButton();
        menubtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 0));

        tabbfoldingtable.setBackground(new java.awt.Color(255, 0, 102));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        addtocartbtn8.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn8.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn8.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn8.setText("ADD TO CART");
        addtocartbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn8ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/nested table 3.jpg"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/nested table 4.jpg"))); // NOI18N

        addtocartbtn9.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn9.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn9.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn9.setText("ADD TO CART");
        addtocartbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn9ActionPerformed(evt);
            }
        });

        addtocartbtn10.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn10.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn10.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn10.setText("ADD TO CART");
        addtocartbtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn10ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/nested table 2.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/nested table 1.jpg"))); // NOI18N

        addtocartbtn12.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn12.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn12.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn12.setText("ADD TO CART");
        addtocartbtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn12ActionPerformed(evt);
            }
        });

        nameitemlabel20.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel20.setText("check sheesham nesting");

        nameitemlabel21.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14)); // NOI18N
        nameitemlabel21.setText("Coleman nesting tables");

        nameitemlabel22.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel22.setText("loera nesting tables");

        nameitemlabel23.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel23.setText("Maguire nesting tables");

        nameitemlabel24.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel24.setText("PRICE: RS 80,000");

        nameitemlabel25.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel25.setText("PRICE: RS 59,000");

        nameitemlabel26.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel26.setText("PRICE: RS 69,000");

        nameitemlabel27.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel27.setText("PRICE: RS 75,000");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(addtocartbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(addtocartbtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(addtocartbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(addtocartbtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameitemlabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(nameitemlabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(59, 59, 59)
                                .addComponent(jLabel12))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel10)
                                        .addGap(40, 40, 40))
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nameitemlabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                                        .addComponent(jSeparator9)
                                        .addComponent(jSeparator10))))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameitemlabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameitemlabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)))
                        .addContainerGap(131, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameitemlabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(nameitemlabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(147, 147, 147))))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(nameitemlabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(516, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(nameitemlabel20)
                        .addGap(73, 73, 73)
                        .addComponent(nameitemlabel26)))
                .addGap(18, 18, 18)
                .addComponent(addtocartbtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(nameitemlabel21)))
                .addGap(35, 35, 35)
                .addComponent(addtocartbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel11))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(nameitemlabel22)
                        .addGap(98, 98, 98)
                        .addComponent(nameitemlabel25)))
                .addGap(18, 18, 18)
                .addComponent(addtocartbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(nameitemlabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameitemlabel24)
                        .addGap(87, 87, 87)))
                .addComponent(addtocartbtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(684, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(553, 553, 553)
                    .addComponent(nameitemlabel27)
                    .addContainerGap(1547, Short.MAX_VALUE)))
        );

        jScrollPane3.setViewportView(jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tabbfoldingtable.addTab("Nested Tables", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/folding table 1.jpg"))); // NOI18N

        addtocartbtn5.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn5.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn5.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn5.setText("ADD TO CART");
        addtocartbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn5ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/folding table 2.jpg"))); // NOI18N

        addtocartbtn6.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn6.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn6.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn6.setText("ADD TO CART");
        addtocartbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn6ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/folding table 3.jpg"))); // NOI18N

        addtocartbtn7.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn7.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn7.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn7.setText("ADD TO CART");
        addtocartbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn7ActionPerformed(evt);
            }
        });

        nameitemlabel17.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel17.setText("Beach folding");

        nameitemlabel18.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel18.setText("Beach folding round");

        nameitemlabel19.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel19.setText("Blankey folding");

        nameitemlabel28.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel28.setText("PRICE: RS 38,000");

        nameitemlabel29.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel29.setText("PRICE: RS 28,000");

        nameitemlabel30.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel30.setText("PRICE: RS 41,000");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(nameitemlabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(nameitemlabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel7))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(nameitemlabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nameitemlabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(nameitemlabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(nameitemlabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(238, 238, 238))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(addtocartbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(addtocartbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(addtocartbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel6))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(nameitemlabel19)
                        .addGap(59, 59, 59)
                        .addComponent(nameitemlabel30)))
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(addtocartbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(addtocartbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(37, 37, 37)
                                .addComponent(addtocartbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(nameitemlabel17)
                                .addGap(57, 57, 57)
                                .addComponent(nameitemlabel28))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(nameitemlabel18)
                        .addGap(52, 52, 52)
                        .addComponent(nameitemlabel29)))
                .addContainerGap(1229, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel6);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        tabbfoldingtable.addTab("Folding Tables", jPanel4);

        jPanel2.setBackground(new java.awt.Color(153, 0, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/coffe_table .jpg"))); // NOI18N

        addtocartbtn.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn.setText("ADD TO CART");
        addtocartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/coffee_table.jpg"))); // NOI18N

        addtocartbtn1.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn1.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn1.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn1.setText("ADD TO CART");
        addtocartbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/coffe_table_2.jpg"))); // NOI18N

        addtocartbtn2.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn2.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn2.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn2.setText("ADD TO CART");
        addtocartbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn2ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/side tabel 1.jpg"))); // NOI18N

        addtocartbtn3.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn3.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn3.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn3.setText("ADD TO CART");
        addtocartbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn3ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/furniture_shop/side table 2.jpg"))); // NOI18N

        addtocartbtn4.setBackground(new java.awt.Color(102, 0, 0));
        addtocartbtn4.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N
        addtocartbtn4.setForeground(new java.awt.Color(255, 255, 255));
        addtocartbtn4.setText("ADD TO CART");
        addtocartbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartbtn4ActionPerformed(evt);
            }
        });

        nameitemlabel12.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel12.setText("Bolanberg side table");

        nameitemlabel13.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel13.setText("North Shore side tables");

        nameitemlabel14.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel14.setText("rayna coffee table");

        nameitemlabel15.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel15.setText("Helios coffee tables");

        nameitemlabel16.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        nameitemlabel16.setText("bronson coffee table");

        nameitemlabel31.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel31.setText("PRICE: RS 101,000");

        nameitemlabel32.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel32.setText("PRICE: RS 90,000");

        nameitemlabel33.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel33.setText("PRICE: RS 93,000");

        nameitemlabel34.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel34.setText("PRICE: RS 32,000");

        nameitemlabel35.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        nameitemlabel35.setText("PRICE: RS 20,000");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(nameitemlabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addGap(61, 61, 61)
                                    .addComponent(nameitemlabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addComponent(jLabel5))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(nameitemlabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(18, 18, 18))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(nameitemlabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel1)
                                    .addGap(10, 10, 10))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(nameitemlabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)))))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(267, 267, 267))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(addtocartbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(addtocartbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(addtocartbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(addtocartbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(addtocartbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(nameitemlabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(513, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(nameitemlabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(567, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(nameitemlabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(635, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(nameitemlabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(651, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addComponent(nameitemlabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(627, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(nameitemlabel16)
                        .addGap(44, 44, 44)
                        .addComponent(nameitemlabel31)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addtocartbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(addtocartbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(nameitemlabel14)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(addtocartbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addtocartbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(nameitemlabel12)
                        .addGap(66, 66, 66)
                        .addComponent(nameitemlabel34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addtocartbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(970, Short.MAX_VALUE)
                    .addComponent(nameitemlabel13)
                    .addGap(661, 661, 661)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(647, 647, 647)
                    .addComponent(nameitemlabel15)
                    .addContainerGap(984, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(766, 766, 766)
                    .addComponent(nameitemlabel32)
                    .addContainerGap(871, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(451, 451, 451)
                    .addComponent(nameitemlabel33)
                    .addContainerGap(1186, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(1089, Short.MAX_VALUE)
                    .addComponent(nameitemlabel35)
                    .addGap(548, 548, 548)))
        );

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1301, 1301, 1301))
        );

        tabbfoldingtable.addTab("Coffe & Side Tables", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));

        headingTable.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        headingTable.setForeground(new java.awt.Color(255, 255, 255));
        headingTable.setText("TABLES");

        checkoutbtn.setBackground(new java.awt.Color(0, 0, 0));
        checkoutbtn.setFont(new java.awt.Font("Segoe Print", 3, 12)); // NOI18N
        checkoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutbtn.setText("CHECK OUT");
        checkoutbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkoutbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutbtnActionPerformed(evt);
            }
        });

        menubtn.setBackground(new java.awt.Color(0, 0, 0));
        menubtn.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        menubtn.setForeground(new java.awt.Color(255, 255, 255));
        menubtn.setText("MENU");
        menubtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menubtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headingTable)
                .addGap(199, 199, 199)
                .addComponent(checkoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(checkoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(headingTable)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabbfoldingtable)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbfoldingtable, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addtocartbtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn10ActionPerformed
        // TODO add your handling code here:
        String Product = "Check sheesham nesting";
        String Qty = "1";
        String Price = "69000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn10ActionPerformed

    private void menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubtnActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menubtnActionPerformed

    private void checkoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutbtnActionPerformed
        // TODO add your handling code here:
        Billing b = new Billing();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkoutbtnActionPerformed

    private void addtocartbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn8ActionPerformed
        // TODO add your handling code here:
        String Product = "Coleman Nesting Table";
        String Qty = "1";
        String Price = "75000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn8ActionPerformed

    private void addtocartbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn9ActionPerformed
        // TODO add your handling code here:
        String Product = "Loera Nesting Table";
        String Qty = "1";
        String Price = "59000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn9ActionPerformed

    private void addtocartbtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn12ActionPerformed
        // TODO add your handling code here:
        String Product = "Maguire Nesting Table";
        String Qty = "1";
        String Price = "80000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn12ActionPerformed

    private void addtocartbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn5ActionPerformed
        // TODO add your handling code here:
        String Product = "Blankey Folding";
        String Qty = "1";
        String Price = "41000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn5ActionPerformed

    private void addtocartbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn6ActionPerformed
        // TODO add your handling code here:
        String Product = "Beach Folding Round";
        String Qty = "1";
        String Price = "28000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn6ActionPerformed

    private void addtocartbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn7ActionPerformed
        // TODO add your handling code here:
        String Product = "Beach Folding";
        String Qty = "1";
        String Price = "38000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn7ActionPerformed

    private void addtocartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtnActionPerformed
        // TODO add your handling code here:
        String Product = "Bronson Coffee Table";
        String Qty = "1";
        String Price = "101000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtnActionPerformed

    private void addtocartbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn1ActionPerformed
        // TODO add your handling code here:
        String Product = "Rayna Coffee Table";
        String Qty = "1";
        String Price = "93000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn1ActionPerformed

    private void addtocartbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn2ActionPerformed
        // TODO add your handling code here:
        String Product = "Helios Coffee Table";
        String Qty = "1";
        String Price = "90000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn2ActionPerformed

    private void addtocartbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn4ActionPerformed
        // TODO add your handling code here:
        String Product = "North Shore Side Table";
        String Qty = "1";
        String Price = "20000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn4ActionPerformed

    private void addtocartbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartbtn3ActionPerformed
        // TODO add your handling code here:
        String Product = "Bolanberg Side Table";
        String Qty = "1";
        String Price = "32000";
 
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Register the mysql driver
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/furniture_shop","root","");
            insert = con1.prepareStatement("insert into billing (Product, Qty, Price)values(?,?,?)");
            insert.setString(1,Product);
            insert.setString(2,Qty);
            insert.setString(3,Price);
            insert.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Saved");
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(chair.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_addtocartbtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtocartbtn;
    private javax.swing.JButton addtocartbtn1;
    private javax.swing.JButton addtocartbtn10;
    private javax.swing.JButton addtocartbtn12;
    private javax.swing.JButton addtocartbtn2;
    private javax.swing.JButton addtocartbtn3;
    private javax.swing.JButton addtocartbtn4;
    private javax.swing.JButton addtocartbtn5;
    private javax.swing.JButton addtocartbtn6;
    private javax.swing.JButton addtocartbtn7;
    private javax.swing.JButton addtocartbtn8;
    private javax.swing.JButton addtocartbtn9;
    private javax.swing.JButton checkoutbtn;
    private javax.swing.JLabel headingTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton menubtn;
    private javax.swing.JLabel nameitemlabel12;
    private javax.swing.JLabel nameitemlabel13;
    private javax.swing.JLabel nameitemlabel14;
    private javax.swing.JLabel nameitemlabel15;
    private javax.swing.JLabel nameitemlabel16;
    private javax.swing.JLabel nameitemlabel17;
    private javax.swing.JLabel nameitemlabel18;
    private javax.swing.JLabel nameitemlabel19;
    private javax.swing.JLabel nameitemlabel20;
    private javax.swing.JLabel nameitemlabel21;
    private javax.swing.JLabel nameitemlabel22;
    private javax.swing.JLabel nameitemlabel23;
    private javax.swing.JLabel nameitemlabel24;
    private javax.swing.JLabel nameitemlabel25;
    private javax.swing.JLabel nameitemlabel26;
    private javax.swing.JLabel nameitemlabel27;
    private javax.swing.JLabel nameitemlabel28;
    private javax.swing.JLabel nameitemlabel29;
    private javax.swing.JLabel nameitemlabel30;
    private javax.swing.JLabel nameitemlabel31;
    private javax.swing.JLabel nameitemlabel32;
    private javax.swing.JLabel nameitemlabel33;
    private javax.swing.JLabel nameitemlabel34;
    private javax.swing.JLabel nameitemlabel35;
    private javax.swing.JTabbedPane tabbfoldingtable;
    // End of variables declaration//GEN-END:variables
}
